### ISSUE TITLE
remove concurrency settigns

### ISSUE THREAD

**Issue by ferantivero** [mspnp/serverless-automation#3]
as per the official [docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-best-practices#configure-host-behaviors-to-better-handle-concurrency), it's possible to manage  concurrency per instance in Azure Functions. 

That being said, we want to remove the current configuration as this is not aligned with our scenarios.

**Comment by kirpasingh** [comment]
It was already addressed via [PR](https://github.com/mspnp/serverless-automation/pull/4), but for some reason, issue remained open!
